# Generated by Django 3.2.19 on 2025-04-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='reasoning_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
