# Generated by Django 3.2.19 on 2025-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_reasoning_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_type',
            field=models.CharField(choices=[('deepseek-chat', 'DeepSeek Chat'), ('deepseek-reasoner', 'DeepSeek Reasoner')], default='deepseek-chat', max_length=20),
        ),
    ]
